---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  handlers:
    - name: restart sshd
      command: systemctl restart sshd.service

  tasks:
    - name: Adjust vagrant ssh config
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PasswordAuthentication no"
        line: "PasswordAuthentication no"
        state: present
      notify: restart sshd

    - name: Insert local key into authorized_keys
      become_user: vagrant
      blockinfile:
        block: "{{ lookup('file', '{{ personal_key_path }}')}}"
        dest: "{{ authorized_keys_path }}"

    - name: Installing dependencies
      yum: name={{ item }} state=present
      with_items:
        - epel-release
        - git
        - curl
        - vim
        - gcc
        - gcc-c++
        - glibc-devel
        - make
        - ncurses-devel
        - openssl-devel
        - autoconf
        - java-1.8.0-openjdk-devel
        - wget
        - unixODBC-devel
        - unzip
        - which

    - name: Installing nodejs
      yum:
        name: nodejs
        state: present

    - name: Install Erlang
      yum:
        name: "{{ erlang_distribution_url }}"
        state: present

    - name: Creating elixir directory
      file:
       path: "{{ elixir_home }}"
       state: directory
       mode: 0751

    - name: Downloading elixir precompiled
      unarchive:
        src: "{{ elixir_precompiled_url }}"
        dest: "{{ elixir_home }}"
        remote_src: True
        creates: "{{ elixir_home }}/VERSION"

    - name: Creating symbolic links for elixir
      file:
        src:  "{{ elixir_home }}/bin/{{ item.name }}"
        dest: "/usr/bin/{{ item.name }}"
        state: link
      with_items:
        - { name: 'elixir' }
        - { name: 'elixirc' }
        - { name: 'iex' }
        - { name: 'mix' }

    - name: Install hex package manager
      become_user: vagrant
      shell: mix local.hex --force

    - name: Installing Phoenix
      become_user: vagrant
      shell: "mix archive.install {{ phoenix_url }} --force"
